version: "3.8"

secrets:
    config_json:
        file: secrets.json

services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '~/docker/containers/nginx/html:/etc/nginx/html'
            - '~/docker/containers/nginx/config:/etc/nginx'
            - '~/docker/containers/certbot/conf:/etc/letsencrypt'
            - '~/docker/containers/certbot/www:/var/www/certbot'
        logging:
            options:
                max-size: 1m
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - '~/docker/containers/certbot/conf:/etc/letsencrypt'
            - '~/docker/containers/certbot/www:/var/www/certbot'
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    foundry:
        image: felddy/foundryvtt:release
        container_name: foundry
        init: true
        restart: unless-stopped
        volumes:
                - '~/docker/containers/foundry/data:/data'
        environment:
                - FOUNDRY_UID=${PUID}
                - FOUNDRY_GID=${PGID}
                - TIMEZONE=${TZ}
                - FOUNDRY_HOSTNAME=forge.${DOMAIN_NAME}
                - FOUNDRY_AWS_CONFIG=/data/Config/awsConfig.json
                - FOUNDRY_PROXY_PORT=443
                - FOUNDRY_PROXY_SSL=true
        secrets:
            - source: config_json
              target: config.json
